name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  linux:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@2eae45db285e407f22119950686d47e1101e071b # 1.88.0
        with:
          toolchain: 1.88.0
          components: clippy,rustfmt

      - name: Install just
        uses: taiki-e/install-action@b20dedce73af6905cdc30d6611090c9b67557c8d # v2.85.12
        with:
          tool: just@1.55.1

      - name: Cache Rust build
        uses: Swatinem/rust-cache@63fed3e2fecf6f7b51dc6f043341b79ef82a9ae7 # v2.9.2
        with:
          cache-workspace-crates: true

      - name: Run CI
        run: just ci

  platform:
    name: ${{ matrix.name }}
    needs: linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@2eae45db285e407f22119950686d47e1101e071b # 1.88.0
        with:
          toolchain: 1.88.0
          components: clippy,rustfmt

      - name: Install just
        uses: taiki-e/install-action@b20dedce73af6905cdc30d6611090c9b67557c8d # v2.85.12
        with:
          tool: just@1.55.1

      - name: Cache Rust build
        uses: Swatinem/rust-cache@63fed3e2fecf6f7b51dc6f043341b79ef82a9ae7 # v2.9.2
        with:
          cache-workspace-crates: true

      - name: Run CI
        run: just ci
